#.travis.yml
    
language: node_js
node_js: 
 - "8.9"
  
sudo: required
dist: trusty
 
addons:
 chrome: stable
 sonarcloud:
  organization: "bigbrotter-01"
    
branches:
 only:
 - master

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - npm install -g @angular/cli

script:
  - ng test
  - sonar-scanner