#.travis.yml
    
language: node_js
node_js:
  - "8.9"
  
 dist: trusty
 addons:
    chrome: stable
    
branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng test

after_success:
  - ng serve

notifications: